export const TEST_IDS = {
  helpBox: 'Configuration help box',
  dropZone: 'Configuration drop zone',
  pasteArea: 'Configuration text area',
  pasteJwtButton: 'Paste JWT button',
  resetJwtButton: 'Reset JWT button',
  jwtForm: 'JWT form',
  authTypeButtonJWT: 'JWT button',
  authTypeButtonGCE: 'GCE button',
  privateKeyPathInput: 'Private Key Path Input',
  privateKeyInput: 'Private Key Input',
  fillJwtManuallyButton: 'Fill JWT info manually',
  linkPrivateKeyPath: 'Show private key path input',
  linkPrivateKey: 'Show private key input',
};
