name: CI
permissions:
  contents: read

on:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn typecheck
      - run: yarn test:ci
      - run: yarn build
      - run: yarn verify-types
      - run: yarn lint:package
